name       : haskell-unliftio-core
version    : 0.2.0.0
release    : 2
source     :
    - https://hackage.haskell.org/package/unliftio-core-0.2.0.0/unliftio-core-0.2.0.0.tar.gz : e504c705f5ef0a2a5972a1d66f6b4530064fc1f9327ca0ac42e024f741a64810
license    : MIT
component  : programming.haskell
summary    : Provides the core MonadUnliftIO typeclass, instances for base and transformers, and basic utility functions.
description: |
    Provides the core MonadUnliftIO typeclass, instances for base and transformers, and basic utility functions.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
