name       : haskell-unliftio-core
version    : 0.1.1.0
release    : 1
source     :
    - https://hackage.haskell.org/package/unliftio-core-0.1.1.0/unliftio-core-0.1.1.0.tar.gz : 7550b017d87af53ae3e0d3b8524e24a77faf739073f35e40663454a9e9752385
license    : MIT
component  : programming.haskell
summary    : Provides the core MonadUnliftIO typeclass, instances for base and transformers, and basic utility functions.
description: |
    Provides the core MonadUnliftIO typeclass, instances for base and transformers, and basic utility functions. 
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
